name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: Install Pa11y
      run: npm install -g pa11y

    - name: Run Accessibility Tests
      env:
        target_url: ${{ secrets.target_url }}
      run: pa11y "%target_url%"
